// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyScriptureJournal.Migrations
{
    [DbContext(typeof(MyScriptureJournalContext))]
    [Migration("20221104202713_lessNotes")]
    partial class lessNotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MyScriptureJournal.Models.Canon", b =>
                {
                    b.Property<int>("CanonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CanonID");

                    b.ToTable("Canon");
                });

            modelBuilder.Entity("MyScriptureJournal.Models.ScriptRef", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Canon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Verses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lessNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ScriptRef");
                });
#pragma warning restore 612, 618
        }
    }
}
